# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30df526e9c5bf1f825f4d4a10c89e0c508839233a74fee69b74c7fbf1dd24bbf66ea959f389901a9ad66b9ad4134149f1db9ba97c98afba7566984a9730f19a

test:
  secret_key_base: f7d7f7f3cb1507b1dd9970a1ed0c5f084fbde00864398a770c3ffbcf20d21e1cf2de2c9540bf76fc8499683be1466aac35e4bf04997ef88281513a221e6c1e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
